name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache external
        uses: actions/cache@v2
        with:
          path: |
            external
          key: ${{ runner.os }}-external

      - name: Build
        run: make build

      - name: Test
        run: make test
