name: ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache external
        uses: actions/cache@v2
        with:
          path: |
            external
          key: external-${{ hashFiles('cmake/*') }}

      - name: Cache Library for Tests
        uses: actions/cache@v2
        with:
          path: |
            tests/lib
          key: tests_lib-${{ hashFiles('tests/CMakeLists.txt') }}

      - name: Build
        run: make build -j 4

      - name: Test
        run: make test
